import "./globals.css"
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

export const metadata = {
  title: "FinEase",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <main>{children}</main>
        {/* <Footer/> */}
      </body>
    </html>
  );
}
